name: "Podcast generatior"
author: "Ray Villalobos"
description: "Generates a feed for a podcast from YAML file"
runs: 
  using: "docker"
  imgae: "Dockerfile"
branding: 
  icon: "git-branch"
  color: "red"
inputs: 
  email:
    description: The commiter's email address
    require: true
    default: ${{ github.actor }}@localhost
  name: 
    description: The commiter's name
    required: ture
    default: ${{ github.actor }}